In [50]:
import pandas as pd

# Створення набору даних із 10 клієнтів для Варіанта 1 (Київ: ціна = 850)
data = [
    {"вік": 25, "дохід": 18000, "кількість": 3, "місто_доставки": "Київ"},
    {"вік": 34, "дохід": 35000, "кількість": 2, "місто_доставки": "Львів"},
    {"вік": 45, "дохід": 60000, "кількість": 4, "місто_доставки": "Одеса"},
    {"вік": 22, "дохід": 15000, "кількість": 1, "місто_доставки": "Харків"},
    {"вік": 50, "дохід": 85000, "кількість": 5, "місто_доставки": "Київ"},
    {"вік": 29, "дохід": 24000, "кількість": 3, "місто_доставки": "Львів"},
    {"вік": 41, "дохід": 50000, "кількість": 2, "місто_доставки": "Одеса"},
    {"вік": 60, "дохід": 40000, "кількість": 3, "місто_доставки": "Харків"},
    {"вік": 38, "дохід": 45000, "кількість": 4, "місто_доставки": "Київ"},
    {"вік": 27, "дохід": 20000, "кількість": 2, "місто_доставки": "Львів"}
]

df_clients = pd.DataFrame(data)
print("Набір даних клієнтів:")
display(df_clients)

Набір даних клієнтів:

   вік  дохід  кількість місто_доставки
0   25  18000          3           Київ
1   34  35000          2          Львів
2   45  60000          4          Одеса
3   22  15000          1         Харків
4   50  85000          5           Київ
5   29  24000          3          Львів
6   41  50000          2          Одеса
7   60  40000          3         Харків
8   38  45000          4           Київ
9   27  20000          2          Львів

In [51]:
# Базова ціна для Варіанта 1 (Київ)
BASE_PRICE = 850

# 1. Сума замовлення
df_clients["сума_замовлення"] = BASE_PRICE * df_clients["кількість"]

# 2. Частка доходу, яку клієнт витрачає на замовлення
df_clients["частка_доходу"] = df_clients["сума_замовлення"] / df_clients["дохід"]

print("З новими похідними змінними:")
display(df_clients[["сума_замовлення", "частка_доходу"]])

З новими похідними змінними:

   сума_замовлення  частка_доходу
0             2550       0.141667
1             1700       0.048571
2             3400       0.056667
3              850       0.056667
4             4250       0.050000
5             2550       0.106250
6             1700       0.034000
7             2550       0.063750
8             3400       0.075556
9             1700       0.085000

In [52]:
# 1. pd.cut() — рівні за довжиною інтервали
df_clients["вік_група_cut"] = pd.cut(df_clients["вік"], bins=3)
print("Кількість клієнтів у групах через cut (рівні інтервали за віком):")
print(df_clients["вік_група_cut"].value_counts())

# 2. pd.qcut() — рівна кількість спостережень у кожній групі
df_clients["вік_група_qcut"] = pd.qcut(df_clients["вік"], q=3)
print("\nКількість клієнтів у групах через qcut (рівна кількість у кожній групі):")
print(df_clients["вік_група_qcut"].value_counts())

Кількість клієнтів у групах через cut (рівні інтервали за віком):
вік_група_cut
(21.962, 34.667]    5
(34.667, 47.333]    3
(47.333, 60.0]      2
Name: count, dtype: int64

Кількість клієнтів у групах через qcut (рівна кількість у кожній групі):
вік_група_qcut
(21.999, 29.0]    4
(41.0, 60.0]      4
(29.0, 41.0]      2
Name: count, dtype: int64

In [53]:
# Копіюємо змінні для перетворення
age = df_clients["вік"]
income = df_clients["дохід"]

# 1. Min-Max нормалізація (у діапазоні [0, 1])
df_clients["вік_minmax"] = (age - age.min()) / (age.max() - age.min())
df_clients["дохід_minmax"] = (income - income.min()) / (income.max() - income.min())

# 2. Z-оцінка / стандартизація (середнє = 0, std = 1)
df_clients["вік_z"] = (age - age.mean()) / age.std()
df_clients["дохід_z"] = (income - income.mean()) / income.std()

print("Результати масштабування (перші 5 рядків):")
display(df_clients[["вік", "вік_minmax", "вік_z", "дохід", "дохід_minmax", "дохід_z"]].head())

Результати масштабування (перші 5 рядків):

   вік  вік_minmax     вік_z  дохід  дохід_minmax   дохід_z
0   25    0.078947 -0.998784  18000      0.042857 -0.966124
1   34    0.315789 -0.255887  35000      0.285714 -0.191402
2   45    0.605263  0.652099  60000      0.642857  0.947895
3   22    0.000000 -1.246417  15000      0.000000 -1.102839
4   50    0.736842  1.064819  85000      1.000000  2.087192

In [54]:
# 1. One-hot кодування для міста доставки
city_dummies = pd.get_dummies(df_clients["місто_доставки"], prefix="місто")

# 2. Долучення отриманих стовпців до основної таблиці
df_clients = pd.concat([df_clients, city_dummies], axis=1)

print(f"Кількість унікальних міст у даних: {df_clients['місто_доставки'].nunique()}")
print(f"Кількість нових стовпців-індикаторів: {city_dummies.shape[1]}")

print("\Оновлена таблиця після One-Hot кодування:")
display(df_clients.head())

Кількість унікальних міст у даних: 4
Кількість нових стовпців-індикаторів: 4
\Оновлена таблиця після One-Hot кодування:

,вік,дохід,кількість,місто_доставки,сума_замовлення,частка_доходу,вік_група_cut,вік_група_qcut,вік_minmax,дохід_minmax,вік_z,дохід_z,місто_Київ,місто_Львів,місто_Одеса,місто_Харків
0,25,18000,3,Київ,2550,0.141667,"(21.962, 34.667]","(21.999, 29.0]",0.078947,0.042857,-0.998784,-0.966124,True,False,False,False
1,34,35000,2,Львів,1700,0.048571,"(21.962, 34.667]","(29.0, 41.0]",0.315789,0.285714,-0.255887,-0.191402,False,True,False,False
2,45,60000,4,Одеса,3400,0.056667,"(34.667, 47.333]","(41.0, 60.0]",0.605263,0.642857,0.652099,0.947895,False,False,True,False
3,22,15000,1,Харків,850,0.056667,"(21.962, 34.667]","(21.999, 29.0]",0.000000,0.000000,-1.246417,-1.102839,False,False,False,True
4,50,85000,5,Київ,4250,0.050000,"(47.333, 60.0]","(41.0, 60.0]",0.736842,1.000000,1.064819,2.087192,True,False,False,False

### Відповіді на контрольні запитання:

1. **Різниця між pd.cut() і pd.qcut():**
   - `pd.cut()` розбиває числову змінну на інтервали **однакової довжини** (ширини діапазону) незалежно від кількості точок у них. `pd.qcut()` розбиває дані за квантилями, гарантуючи **однакову кількість спостережень** у кожній створеній групі ціною нерівних інтервалів.

2. **Чому для номінальної змінної застосовують one-hot кодування, а не числове (1, 2, 3):**
   - Числовий мапінг створює хибне уявлення про наявність упорядкованості, ранжування чи математичних відстаней між категоріями (наприклад, що категорія «3» більша за «1»). One-hot кодування створює окремі бінарні колонки для кожної категорії, повністю уникаючи штучного впровадження порядку.

3. **Навіщо масштабувати змінні перед методами, чутливими до масштабу:**
   - Алгоритми, які спираються на обчислення геометричних відстаней (метод k-найближчих сусідів, метод головних компонент, нейронні мережі) або використовують регуляризацію в регресії, чутливі до абсолютних масштабів. Без масштабування змінні з більшими числовими значеннями домінуватимуть над іншими, спотворюючи результати моделювання.

4. **Чому похідна змінна (наприклад, частка доходу) часто корисніша за вихідні складники:**
   - Похідні змінні об'єднують кілька метрик в один логічний показник, який несе прямий аналітичний чи бізнес-сенс. У нашому прикладі `частка доходу` безпосередньо характеризує фінансове навантаження замовлення на клієнта, чого неможливо побачити, аналізуючи суму замовлення та дохід окремо один від одного.