In [21]:
import pandas as pd

# Завдання 1. Побудова wide-таблиці для Києва (Варіант 1)
wide = pd.DataFrame({
    "місто": ["Київ"],
    "Січ": [78], "Лют": [74], "Бер": [68], "Кві": [58],
    "Тра": [50], "Чер": [44], "Лип": [40], "Сер": [42],
    "Вер": [52], "Жов": [66], "Лис": [76], "Гру": [82]
})

print("Вихідна wide-таблиця:")
display(wide)

Вихідна wide-таблиця:

  місто  Січ  Лют  Бер  Кві  Тра  Чер  Лип  Сер  Вер  Жов  Лис  Гру
0  Київ   78   74   68   58   50   44   40   42   52   66   76   82

In [22]:
# Завдання 2. Приведення до tidy (melt)
tidy = wide.melt(id_vars="місто", var_name="місяць", value_name="хмарність")

print("Tidy-таблиця:")
display(tidy)
print("Форма (shape) tidy-таблиці:", tidy.shape)

Tidy-таблиця:

   місто місяць  хмарність
0   Київ    Січ         78
1   Київ    Лют         74
2   Київ    Бер         68
3   Київ    Кві         58
4   Київ    Тра         50
5   Київ    Чер         44
6   Київ    Лип         40
7   Київ    Сер         42
8   Київ    Вер         52
9   Київ    Жов         66
10  Київ    Лис         76
11  Київ    Гру         82

Форма (shape) tidy-таблиці: (12, 3)

In [23]:
# Завдання 4. Зворотне перетворення (pivot)
back_wide = tidy.pivot(index="місто", columns="місяць", values="хмарність").reset_index()

print("Таблиця після зворотного перетворення pivot:")
display(back_wide)

Таблиця після зворотного перетворення pivot:

місяць місто  Бер  Вер  Гру  Жов  Кві  Лип  Лис  Лют  Сер  Січ  Тра  Чер
0       Київ   68   52   82   66   58   40   76   74   42   78   50   44

In [24]:
# Завдання 5. Запис у файли
tidy.to_csv("variant.csv", index=False)
tidy.to_json("variant.json", orient="records", force_ascii=False)

# Читання назад
reloaded_csv = pd.read_csv("variant.csv")
reloaded_json = pd.read_json("variant.json")

print("Перевірка CSV (shape):", reloaded_csv.shape)
print("Перевірка JSON (shape):", reloaded_json.shape)

Перевірка CSV (shape): (12, 3)
Перевірка JSON (shape): (12, 3)

### Відповіді на контрольні запитання:

1. **Чому стовпець "місто" — номінальна шкала, а стовпець "хмарність" — шкала відношень:**
   - Стовпець "місто" містить категорії без будь-якого кількісного чи порядку (назви об'єктів не можна порівнювати «більше/менше»), тому це номінальна шкала.
   - Стовпець "хмарність" вимірюється у відсотках із наявністю абсолютного нуля (0% означає нульову хмарність), що дозволяє порівнювати значення через кратність (наприклад, 80% — це вдвічі більше за 40%), тому це шкала відношень.

2. **Чому вихідна wide-таблиця не вважається tidy, і що змінюється після melt():**
   - Wide-таблиця порушує головний принцип tidy data: значення однієї змінної ("хмарність") були розкидані по заголовках кількох стовпців (назви місяців). Після застосування `melt()` кожен рядок починає представляти одне конкретне спостереження (місто + місяць + показник хмарності).

3. **Чим формат CSV принципово відрізняється від JSON:**
   - CSV є плоскою табличною структурою, яка описує дані через текстові рядки та розмежувачі (коми), що робить її максимально простою й легкою, але менш гнучкою для вкладених структур. JSON базується на об'єктній мові (пари ключ-значення) і зберігає повну інформацію про тип даних та структуру у вигляді масиву словників, що робить його зручним для веб-додатків та складних ієрархічних даних.