In [15]:
import pandas as pd

# Дані для Варіанта 1 (Київ)
months = ["Січ", "Лют", "Бер", "Кві", "Tра", "Чер", "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]
avg_temp = [-4, -3, 2, 9, 15, 19, 21, 20, 14, 8, 2, -2]
precip = [38, 36, 38, 41, 53, 74, 84, 69, 47, 36, 44, 44]

# Створення DataFrame
df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip,
})

# Перевірка структури
print("Перші рядки DataFrame:")
display(df.head())

print("\nФорма DataFrame (shape):", df.shape)
print("\nТипи даних (dtypes):\n", df.dtypes)

Перші рядки DataFrame:

  month  avg_temp  precip
0   Січ        -4      38
1   Лют        -3      36
2   Бер         2      38
3   Кві         9      41
4   Tра        15      53

Форма DataFrame (shape): (12, 3)

Типи даних (dtypes):
 month       object
avg_temp     int64
precip       int64
dtype: object

In [17]:
# 1. Перевірка індексу за замовчуванням (від 0 до 11)
print("Індекс за замовчуванням:", df.index)

# 2. Заміна індексу на стовпець month та виведення рядка для липня ("Лип") через .loc
df_indexed = df.set_index("month")
print("\nРядок для липня ('Лип'):")
display(df_indexed.loc["Лип"])

# 3. Повернення звичайної нумерації рядків назад
df_reset = df_indexed.reset_index()
print("\nПісля скидання індексу:")
display(df_reset.head(3))

Індекс за замовчуванням: RangeIndex(start=0, stop=12, step=1)

Рядок для липня ('Лип'):

avg_temp    21
precip      84
Name: Лип, dtype: int64

Після скидання індексу:

  month  avg_temp  precip
0   Січ        -4      38
1   Лют        -3      36
2   Бер         2      38

In [18]:
# 1. Встановлюємо числовий індекс від 1 до 12 (номери місяців)
df_num_index = df.copy()
df_num_index.index = range(1, 13)

print("Вибірка через .loc[1:6, 'avg_temp'] (включно з правою межею 6):")
display(df_num_index.loc[1:6, "avg_temp"])

# 2. Вибірка через .iloc[0:6] за позиціями (не включає праву межу 6)
print("\nВибірка через .iloc[0:6] (перші 6 позицій, тобто рядки з мітками 1-6):")
display(df_num_index.iloc[0:6]["avg_temp"])

# 3. Виведення лише стовпців month і precip для всіх рядків
print("\nСтовпці month та precip:")
display(df.loc[:, ["month", "precip"]])

Вибірка через .loc[1:6, 'avg_temp'] (включно з правою межею 6):

1    -4
2    -3
3     2
4     9
5    15
6    19
Name: avg_temp, dtype: int64

Вибірка через .iloc[0:6] (перші 6 позицій, тобто рядки з мітками 1-6):

1    -4
2    -3
3     2
4     9
5    15
6    19
Name: avg_temp, dtype: int64

Стовпці month та precip:

   month  precip
0    Січ      38
1    Лют      36
2    Бер      38
3    Кві      41
4    Tра      53
5    Чер      74
6    Лип      84
7    Сер      69
8    Вер      47
9    Жов      36
10   Лис      44
11   Гру      44

In [19]:
# 1. Місяці, де середня температура вище 15°C
print("Місяці з avg_temp > 15:")
display(df[df["avg_temp"] > 15])

# 2. Місяці, де одночасно avg_temp > 10 і precip > 50 (через &)
print("\nМісяці з avg_temp > 10 і precip > 50:")
display(df[(df["avg_temp"] > 10) & (df["precip"] > 50)])

# 3. Місяці, де avg_temp < 0 або precip > 80 (через |)
print("\nМісяці з avg_temp < 0 або precip > 80:")
display(df[(df["avg_temp"] < 0) | (df["precip"] > 80)])

Місяці з avg_temp > 15:

  month  avg_temp  precip
5   Чер        19      74
6   Лип        21      84
7   Сер        20      69

Місяці з avg_temp > 10 і precip > 50:

  month  avg_temp  precip
4   Tра        15      53
5   Чер        19      74
6   Лип        21      84
7   Сер        20      69

Місяці з avg_temp < 0 або precip > 80:

   month  avg_temp  precip
0    Січ        -4      38
1    Лют        -3      36
6    Лип        21      84
11   Гру        -2      44

In [20]:
# 1. Стовпець avg_temp_f — температура у Фаренгейтах
df["avg_temp_f"] = df["avg_temp"] * 9/5 + 32

# 2. Булевий стовпець is_wet — True, якщо опадів більше середнього по таблиці
mean_precip = df["precip"].mean()
df["is_wet"] = df["precip"] > mean_precip

# 3. Текстовий стовпець season через .apply() за номером місяця (індекс + 1)
def get_season(month_num):
    if month_num in [12, 1, 2]:
        return "зима"
    elif month_num in [3, 4, 5]:
        return "весна"
    elif month_num in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"

# Додаємо тимчасовий стовпець з номером місяця для прикладу apply
df["month_num"] = range(1, 13)
df["season"] = df["month_num"].apply(get_season)
df = df.drop(columns=["month_num"]) # видаляємо допоміжний стовпець

print("Результат з новими обчислюваними стовпцями:")
display(df)

Результат з новими обчислюваними стовпцями:

   month  avg_temp  precip  avg_temp_f  is_wet season
0    Січ        -4      38        24.8   False   зима
1    Лют        -3      36        26.6   False   зима
2    Бер         2      38        35.6   False  весна
3    Кві         9      41        48.2   False  весна
4    Tра        15      53        59.0    True  весна
5    Чер        19      74        66.2    True   літо
6    Лип        21      84        69.8    True   літо
7    Сер        20      69        68.0    True   літо
8    Вер        14      47        57.2   False  осінь
9    Жов         8      36        46.4   False  осінь
10   Лис         2      44        35.6   False  осінь
11   Гру        -2      44        28.4   False   зима

### Відповіді на контрольні запитання:

1. **Чому .loc[1:6] і .iloc[0:6] можуть повернути різну кількість рядків залежно від індексу:**
   - `.loc` здійснює пошук за **мітками** індексу і є **включним** по правому краю (тобто `1:6` поверне мітки від 1 до 6 включно — 6 рядків).
   - `.iloc` працює виключно за **порядковими позиціями** (як стандартні зрізи в Python, де права межа не включається: `0:6` бере позиції від 0 до 5, тобто перші 6 елементів). Якщо індекс таблиці не починається з 0 або має текстові мітки, результати `.loc` та `.iloc` відрізнятимуться або викликатимуть помилку.

2. **Чому `df["avg_temp"] > 10 and df["precip"] > 50` викликає помилку, а з `&` — ні:**
   - Логічний оператор `and` у Python намагається оцінити істинність всього об'єкта Series як єдиного цілого (булевого значення), що для колонок з багатьма елементами призводить до помилки `ValueError`.
   - Оператор `&` є побітовим (поелементним) оператором у pandas/NumPy, який порівнює кожен рядок окремо. При цьому кожна умова обов'язково має бути взята в круглі дужки через високий пріоритет оператора `&`.

3. **Різниця між стовпцем, створеним формулою, і створеним через `.apply()`:**
   - Стовпець, створений векторизованою формулою (наприклад, математичними операціями над усім Series), обчислюється всередині бібліотеки на рівні оптимізованого коду C однією операцією для всього стовпця без циклів Python, що працює миттєво.
   - Метод `.apply()` застосовує передану Python-функцію до кожного елемента (або рядка) окремо у вигляді циклу. Це зручно для складної логіки з розгалуженнями (`if-elif-else`), але працює значно повільніше на великих масивах даних.